### ISSUE TITLE
Text on top of image

### ISSUE THREAD

**Issue by katiemcpeak** [katiemcpeak/dsn1676-assignment-1#1]
Hello Thomas, I was wondering if you could help me figure out how to put the text I have added on the middle graphic above it. I have looked up multiple ways of doing it and the closest I got was the text was on top of the image but the text was squished and illegible. 

![screen shot 2015-01-11 at 4 34 31 pm](https://cloud.githubusercontent.com/assets/6340303/5696932/c342d252-99af-11e4-97ae-3a6144fe5c05.png)

Let me know what you think.
@thomasjbradley

**Comment by katiemcpeak** [comment]
http://katiemcpeak.github.io/dsn1676-assignment-1/

**Comment by thomasjbradley** [comment]
The brown image should probably be a background image instead of an `img` tag so that it can sit behind the text.

**Comment by katiemcpeak** [comment]
ok great, now I have this which is better however when I play with width and height the background starts repeating itself and I put no repeat but it's not working.

![screen shot 2015-01-11 at 4 52 11 pm](https://cloud.githubusercontent.com/assets/6340303/5697008/54fef9d0-99b2-11e4-9fe0-818dcd259762.png)

**Comment by thomasjbradley** [comment]
How have you put in `no-repeat`.
You can commit and sync and I can look online if you'd like.

**Comment by katiemcpeak** [comment]
background-repeat: no-repeat;

**Comment by katiemcpeak** [comment]
p {
    background-repeat: no-repeat;
    background-image: url("../images/middle-graphic.png");
    color: white;
    padding: 0;
    margin: 0;
}

**Comment by katiemcpeak** [comment]
I fixed it, I put the background image on the <div> instead of the <p>

**Comment by katiemcpeak** [comment]
I fixed it :) I put the image on the div instead of the paragraph and it worked
